# Generated by Django 3.2 on 2021-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('dec', models.CharField(blank=True, max_length=200, null=True)),
                ('files', models.FileField(upload_to='devoirs')),
                ('dt', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('dec', models.CharField(blank=True, max_length=200, null=True)),
                ('dt', models.TimeField()),
                ('files', models.FileField(upload_to='document')),
            ],
        ),
        migrations.RemoveField(
            model_name='cour',
            name='des',
        ),
        migrations.AddField(
            model_name='cour',
            name='dec',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cour',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
