# Generated by Django 3.2 on 2021-05-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210513_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='dt',
        ),
        migrations.AddField(
            model_name='cour',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='dtf',
            field=models.DateField(default='2020-3-3'),
        ),
        migrations.AddField(
            model_name='document',
            name='cour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content.cour'),
        ),
    ]
