# Generated by Django 3.2 on 2021-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_cour_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
    ]
