# Generated by Django 3.2 on 2021-05-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210519_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
