# Generated by Django 3.2 on 2021-05-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_cour_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='dtf',
        ),
        migrations.AddField(
            model_name='devoir',
            name='cour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content.cour'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='dt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='files',
            field=models.FileField(upload_to='Docs'),
        ),
    ]
