# Generated by Django 3.2 on 2021-05-24 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0012_comment_doc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cour',
            options={'ordering': ('titre', 'dec')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='doc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.document'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
