# Generated by Django 3.2 on 2021-06-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210524_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cour',
            options={},
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=30, null=True)),
                ('dec', models.TextField(max_length=300)),
                ('dt', models.DateField(auto_now=True)),
                ('cour', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content.cour')),
            ],
        ),
    ]
