# Generated by Django 3.2 on 2021-06-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210606_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
    ]
