# Generated by Django 3.2 on 2021-06-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_annonce_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
